### ISSUE TITLE
Problema con la migración actual y docker

### ISSUE THREAD

**Issue by yesgarfue** [pescaito-team/pescaito-hub#38]
Al crear una imagen usando docker no reconoce la migracion actual, las tablas se crean pero no se popula la DB.

**Comment by yesgarfue** [comment]
- La migración 001 fue eliminada por lo que daba error al intentar correr el contenedor.
- Se ha recuperado la migración 001 y se ha modificado tomando en cuenta f91485060c59_titulo_que_quieras.py.

**Comment by yesgarfue** [comment]
Algunos workflows están fallando porque sus correcciones se encuentran en la rama develop. Excepto por esto, todo lo demás está funcionando correctamente.

**Comment by aloporsan** [comment]
Las migraciones funcionan ya. lo que no se es si funcionarań en DOCKER... Ya funcionan en todo el proyecto al menos. Dejo que pruebes el DOCKER a ver si hay éxito con el hotfix

**Comment by yesgarfue** [comment]
Las migraciones funcionan correctamente para docker, queda modificar detalles que no tienen que ver con migraciones ni otras cosas del proyecto. Cerrare esta issue y creare una propia de docker.
